#!/bin/bash

# pull the library
smlpkg sync
echo "library sync'ed"

# downloads the words.txt dataset
mkdir -p data
curl https://raw.githubusercontent.com/dwyl/english-words/refs/heads/master/words.txt > data/words.txt
echo "data/words.txt initialized"

# report the number of cpus
echo "number of cpus: $(scripts/cpu_count)"